### ISSUE TITLE
Meet with EK to figure out error

### ISSUE THREAD

**Issue by vonwenckstern** [EmbeddedMontiArc/EmbeddedMontiArc.github.io#3]
Hi,
today we tried out the online IDE at EK's chrome browser again. It quit with an error having no error message.
But it worked on Edge browser.

My guess is that he cannot build up his virtual file system. But the best way is you both meet or skype to fix this error.
I want to show the result Prof. Rumpe soon, and there it should not crash. So the best is we eliminate this error.

**Comment by 0xJMR** [comment]
From all the people I have forced to test the system, he is the first one to experience a concrete problem with the VFS. If he shouldn't see this message, I would appreciate it if you could ask him, the next time you see him, to send me a proposal for a meeting.
On a side note, I assume that you are not experiencing any issues concerning the VFS?

**Comment by vonwenckstern** [comment]
No, I have no problems.
But the problem is that we did also not see the error at the Chrome console -- otherwise I would send it to you.
But EK says that he uses the newest browser version.

@EvgenyKusmenko please tell @0xJMR when you have time this week to meet him or skype 20 min with him.

**Comment by 0xJMR** [comment]
A reinstallation of the Chrome browser seems to have fixed this issue.
